### ISSUE TITLE
import of sdsstools is slow-ish

### ISSUE THREAD

**Issue by havok2063** [sdss/sdsstools#20]
Importing of `sdsstools` takes 0.5 seconds.   This isn't necessarily slow but since we import it at the beginning of our packages, it can contribute to slow package imports.   From the screenshot you can see the main culprit is `pkg_resources`, which is notoriously slow.  I think this is in part due to the fact it scans the full environment upon import, which incurs a high cost for big environments.  The use in `metadata.py` of `pkg_resources` can be effectively replaced by switching to `importlib.metadata.version` (`importlib_metadata.version` for py<=3.7) for finding package versions, and `packaging.version.parse` for version compliance to PEP440.   This reduces the metadata import time significantly but doesn't necessarily decrease the overall package import due to the use of `pkg_resources` further down in `sdsstools._vendor.releases.docutils...`.  

I'm not necessarily suggesting we fix it at this time, but I'm making an issue for awareness and to keep track of it.   

<img width="1346" alt="sdsstools_importtimes" src="https://user-images.githubusercontent.com/1836302/97994066-e5b28c00-1db2-11eb-93db-4ea63d7653e7.png">

**Comment by albireox** [comment]
Thanks for reporting this and providing a solution. I had noticed this and never liked using `pkg_resources`, but I didn't found a good replacement at the time.

Have a look at #21. It's not using `pkg_resources` anymore, which bring load time down to 0.08s for me, although before it took 0.25 instead of your 0.5s.

I've also moved `releases` to the top directory from `_vendor` so that it can be imported directly and it doesn't need to be pre-imported in `__init__.py`. I tried some fancy lazy loading with `importlib` but it failed in different ways, so I ended up going with the simplest solution.
